apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patchesStrategicMerge:
  - patch-replicas.yaml

images:
  - name: registry.edwardnafornita.com/edwardnafornita-com
    newName: registry.edwardnafornita.com/edwardnafornita-com
    newTag: prod-<SEMVER_TAG>

configMapGenerator:
  - name: portfolio-prod-config
    literals:
      - NODE_ENV=production
