apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - patch-replicas.yaml
images:
  - name: registry.edwardnafornita.com/edwardnafornita-com
    newTag: dev-<COMMIT_SHA>

configMapGenerator:
  - name: portfolio-dev-config
    literals:
      - NODE_ENV=development