name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-image:
    uses: NafornitaProjects/GitHub-Actions/.github/workflows/build-docker-image.yaml@main
    with:
      app_name: edwardnafornita-com
      dockerfile: apps/edwardnafornita-com/Dockerfile
      context: .
    secrets:
      REGISTRY: ${{ secrets.REGISTRY }}

  sync-argocd:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Sync portfolio app in ArgoCD
        uses: argoproj/argocd-action@v2.6.0
        with:
          server: ${{ secrets.ARGOCD_SERVER }}
          username: ${{ secrets.ARGOCD_USERNAME }}
          password: ${{ secrets.ARGOCD_PASSWORD }}
          command: app sync edwardnafornita-com
