name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-image:
    uses: NafornitaProjects/GitHub-Actions/.github/workflows/build-docker-image.yaml@main
    with:
      app_name: edwardnafornita-com
      dockerfile: apps/edwardnafornita-com/Dockerfile
      context: .
    secrets:
      REGISTRY: ${{ secrets.REGISTRY }}

  sync-argocd:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Sync portfolio app in Argo CD
        uses: clowdhaus/argo-cd-action/@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        with:
          version: "2.6.7"
          command: "app sync portfolio-web"
          options: "--grpc-web --insecure"